<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AutoDepositChest</AssemblyName>
    <RootNamespace>AutoDepositChest</RootNamespace>
    <EnableModDeploy>true</EnableModDeploy>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.0" />
  </ItemGroup>
</Project>