名称: 构建模组

开启:
推送:
分支: [主函数]
 工作流调度:

作业:
构建:
运行环境: windows-latest

步骤:
    - 用途: actions/checkout@v4

    - name: 设置 .NET
用途: actions/setup-dotnet@v4
与:
        dotnet-version: '6.0.x'

    - 名称: 下载游戏引用程序集
运行: |
        git clone --depth 1 https://github.com/StardewModders/mod-reference-assemblies.git "${{ github.workspace }}/StardewValley"

    - 名称: 恢复依赖项
运行：dotnet restore

- 名称：构建
运行: dotnet build --configuration Release

上传工件
使用: actions/upload-artifact@v4
与:
名称: 自动存放箱
路径: bin/Release/net6.0/AutoDepositChest.dll
