name: Build Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '6.0.x'
    - name: Download game reference assemblies
      run: |
        git clone --depth 1 https://github.com/StardewModders/mod-reference-assemblies.git "${{ github.workspace }}/StardewValley"
    - name: Restore dependencies
      run: dotnet restore -p:GamePath="${{ github.workspace }}/StardewValley"
    - name: Build
      run: dotnet build --configuration Release -p:GamePath="${{ github.workspace }}/StardewValley"
    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: AutoDepositChest
        path: bin/Release/net6.0/AutoDepositChest.dll
